# -*- coding: utf-8 -*-
## various codes and expansions in the MARC21 format

music_forms = {
    'an': 'Anthems',
    'bd': 'Ballads',
    'bg': 'Bluegrass music',
    'bl': 'Blues',
    'bt': 'Ballets',
    'ca': 'Chaconnes',
    'cb': 'Chants, Other religions',
    'cc': 'Chant, Christian',
    'cg': 'Concerti grossi',
    'ch': 'Chorales',
    'cl': 'Chorale preludes',
    'cn': 'Canons and rounds',
    'co': 'Concertos',
    'cp': 'Chansons, polyphonic',
    'cr': 'Carols',
    'cs': 'Chance compositions',
    'ct': 'Cantatas',
    'cy': 'Country music',
    'cz': 'Canzonas',
    'df': 'Dance forms',
    'dv': 'Divertimentos, serenades, cassations, divertissements, and notturni',
    'fg': 'Fugues',
    'fl': 'Flamenco',
    'fm': 'Folk music',
    'ft': 'Fantasias',
    'gm': 'Gospel music',
    'hy': 'Hymns',
    'jz': 'Jazz',
    'mc': 'Musical revues and comedies',
    'md': 'Madrigals',
    'mi': 'Minuets',
    'mo': 'Motets',
    'mp': 'Motion picture music',
    'mr': 'Marches',
    'ms': 'Masses',
    'mu': 'Multiple forms',
    'mz': 'Mazurkas',
    'nc': 'Nocturnes',
    'nn': 'Not applicable',
    'op': 'Operas',
    'or': 'Oratorios',
    'ov': 'Overtures',
    'pg': 'Program music',
    'pm': 'Passion music',
    'po': 'Polonaises',
    'pp': 'Popular music',
    'pr': 'Preludes',
    'ps': 'Passacaglias',
    'pt': 'Part-songs',
    'pv': 'Pavans',
    'rc': 'Rock music',
    'rd': 'Rondos',
    'rg': 'Ragtime music',
    'ri': 'Ricercars',
    'rp': 'Rhapsodies',
    'rq': 'Requiems',
    'sd': 'Square dance music',
    'sg': 'Songs',
    'sn': 'Sonatas',
    'sp': 'Symphonic poems',
    'st': 'Studies and exercises',
    'su': 'Suites',
    'sy': 'Symphonies',
    'tc': 'Toccatas',
    'tl': 'Teatro lirico',
    'ts': 'Trio-sonatas',
    'uu': 'Unknown',
    'vi': 'Villancicos',
    'vr': 'Variations',
    'wz': 'Waltzes',
    'za': 'Zarzuelas',
    'zz': 'Other'
    }

music_score = {
    'a': 'Full score',
    'b': 'Full score, miniature or study size',
    'c': 'Accompaniment reduced for keyboard',
    'd': 'Vocal score',
    'e': 'Condensed score or piano-conductor score',
    'g': 'Close score',
    'h': 'Chorus score',
    'i': 'Condensed score',
    'j': 'Performer-conductor part',
    'm': 'Multiple score formats',
    'u': 'Unknown',
    ' ': 'Unknown',
    'z': 'Other'
    }


# http://www.loc.gov/marc/languages/
language_codes = {
    'aar': 'Afar',
    'abk': 'Abkhaz',
    'ace': 'Achinese',
    'ach': 'Acoli',
    'ada': 'Adangme',
    'ady': 'Adygei',
    'afa': 'Afroasiatic (Other)',
    'afh': 'Afrihili (Artificial language)',
    'afr': 'Afrikaans',
    'ain': 'Ainu',
    'ajm': 'Aljamía',
    'aka': 'Akan',
    'akk': 'Akkadian',
    'alb': 'Albanian',
    'ale': 'Aleut',
    'alg': 'Algonquian (Other)',
    'alt': 'Altai',
    'amh': 'Amharic',
    'ang': 'English, Old (ca. 450-1100)',
    'anp': 'Angika',
    'apa': 'Apache languages',
    'ara': 'Arabic',
    'arc': 'Aramaic',
    'arg': 'Aragonese',
    'arm': 'Armenian',
    'arn': 'Mapuche',
    'arp': 'Arapaho',
    'art': 'Artificial (Other)',
    'arw': 'Arawak',
    'asm': 'Assamese',
    'ast': 'Bable',
    'ath': 'Athapascan (Other)',
    'aus': 'Australian languages',
    'ava': 'Avaric',
    'ave': 'Avestan',
    'awa': 'Awadhi',
    'aym': 'Aymara',
    'aze': 'Azerbaijani',
    'bad': 'Banda languages',
    'bai': 'Bamileke languages',
    'bak': 'Bashkir',
    'bal': 'Baluchi',
    'bam': 'Bambara',
    'ban': 'Balinese',
    'baq': 'Basque',
    'bas': 'Basa',
    'bat': 'Baltic (Other)',
    'bej': 'Beja',
    'bel': 'Belarusian',
    'bem': 'Bemba',
    'ben': 'Bengali',
    'ber': 'Berber (Other)',
    'bho': 'Bhojpuri',
    'bih': 'Bihari (Other)',
    'bik': 'Bikol',
    'bin': 'Edo',
    'bis': 'Bislama',
    'bla': 'Siksika',
    'bnt': 'Bantu (Other)',
    'bos': 'Bosnian',
    'bra': 'Braj',
    'bre': 'Breton',
    'btk': 'Batak',
    'bua': 'Buriat',
    'bug': 'Bugis',
    'bul': 'Bulgarian',
    'bur': 'Burmese',
    'byn': 'Bilin',
    'cad': 'Caddo',
    'cai': 'Central American Indian (Other)',
    'cam': 'Khmer',
    'car': 'Carib',
    'cat': 'Catalan',
    'cau': 'Caucasian (Other)',
    'ceb': 'Cebuano',
    'cel': 'Celtic (Other)',
    'cha': 'Chamorro',
    'chb': 'Chibcha',
    'che': 'Chechen',
    'chg': 'Chagatai',
    'chi': 'Chinese',
    'chk': 'Chuukese',
    'chm': 'Mari',
    'chn': 'Chinook jargon',
    'cho': 'Choctaw',
    'chp': 'Chipewyan',
    'chr': 'Cherokee',
    'chu': 'Church Slavic',
    'chv': 'Chuvash',
    'chy': 'Cheyenne',
    'cmc': 'Chamic languages',
    'cop': 'Coptic',
    'cor': 'Cornish',
    'cos': 'Corsican',
    'cpe': 'Creoles and Pidgins, English-based (Other)',
    'cpf': 'Creoles and Pidgins, French-based (Other)',
    'cpp': 'Creoles and Pidgins, Portuguese-based (Other)',
    'cre': 'Cree',
    'crh': 'Crimean Tatar',
    'crp': 'Creoles and Pidgins (Other)',
    'csb': 'Kashubian',
    'cus': 'Cushitic (Other)',
    'cze': 'Czech',
    'dak': 'Dakota',
    'dan': 'Danish',
    'dar': 'Dargwa',
    'day': 'Dayak',
    'del': 'Delaware',
    'den': 'Slavey',
    'dgr': 'Dogrib',
    'din': 'Dinka',
    'div': 'Divehi',
    'doi': 'Dogri',
    'dra': 'Dravidian (Other)',
    'dsb': 'Lower Sorbian',
    'dua': 'Duala',
    'dum': 'Dutch, Middle (ca. 1050-1350)',
    'dut': 'Dutch',
    'dyu': 'Dyula',
    'dzo': 'Dzongkha',
    'efi': 'Efik',
    'egy': 'Egyptian',
    'eka': 'Ekajuk',
    'elx': 'Elamite',
    'eng': 'English',
    'enm': 'English, Middle (1100-1500)',
    'epo': 'Esperanto',
    'esk': 'Eskimo languages',
    'esp': 'Esperanto',
    'est': 'Estonian',
    'eth': 'Ethiopic',
    'ewe': 'Ewe',
    'ewo': 'Ewondo',
    'fan': 'Fang',
    'fao': 'Faroese',
    'far': 'Faroese',
    'fat': 'Fanti',
    'fij': 'Fijian',
    'fil': 'Filipino',
    'fin': 'Finnish',
    'fiu': 'Finno-Ugrian (Other)',
    'fon': 'Fon',
    'fre': 'French',
    'fri': 'Frisian',
    'frm': 'French, Middle (ca. 1300-1600)',
    'fro': 'French, Old (ca. 842-1300)',
    'frr': 'North Frisian',
    'frs': 'East Frisian',
    'fry': 'Frisian',
    'ful': 'Fula',
    'fur': 'Friulian',
    'gaa': 'Gã',
    'gae': 'Scottish Gaelix',
    'gag': 'Galician',
    'gal': 'Oromo',
    'gay': 'Gayo',
    'gba': 'Gbaya',
    'gem': 'Germanic (Other)',
    'geo': 'Georgian',
    'ger': 'German',
    'gez': 'Ethiopic',
    'gil': 'Gilbertese',
    'gla': 'Scottish Gaelic',
    'gle': 'Irish',
    'glg': 'Galician',
    'glv': 'Manx',
    'gmh': 'German, Middle High (ca. 1050-1500)',
    'goh': 'German, Old High (ca. 750-1050)',
    'gon': 'Gondi',
    'gor': 'Gorontalo',
    'got': 'Gothic',
    'grb': 'Grebo',
    'grc': 'Greek, Ancient (to 1453)',
    'gre': 'Greek, Modern (1453-)',
    'grn': 'Guarani',
    'gsw': 'Swiss German',
    'gua': 'Guarani',
    'guj': 'Gujarati',
    'gwi': 'Gwich\'in',
    'hai': 'Haida',
    'hat': 'Haitian French Creole',
    'hau': 'Hausa',
    'haw': 'Hawaiian',
    'heb': 'Hebrew',
    'her': 'Herero',
    'hil': 'Hiligaynon',
    'him': 'Western Pahari languages',
    'hin': 'Hindi',
    'hit': 'Hittite',
    'hmn': 'Hmong',
    'hmo': 'Hiri Motu',
    'hrv': 'Croatian',
    'hsb': 'Upper Sorbian',
    'hun': 'Hungarian',
    'hup': 'Hupa',
    'iba': 'Iban',
    'ibo': 'Igbo',
    'ice': 'Icelandic',
    'ido': 'Ido',
    'iii': 'Sichuan Yi',
    'ijo': 'Ijo',
    'iku': 'Inuktitut',
    'ile': 'Interlingue',
    'ilo': 'Iloko',
    'ina': 'Interlingua (International Auxiliary Language Association)',
    'inc': 'Indic (Other)',
    'ind': 'Indonesian',
    'ine': 'Indo-European (Other)',
    'inh': 'Ingush',
    'int': 'Interlingua (International Auxiliary Language Association)',
    'ipk': 'Inupiaq',
    'ira': 'Iranian (Other)',
    'iri': 'Irish',
    'iro': 'Iroquoian (Other)',
    'ita': 'Italian',
    'jav': 'Javanese',
    'jbo': 'Lojban (Artificial language)',
    'jpn': 'Japanese',
    'jpr': 'Judeo-Persian',
    'jrb': 'Judeo-Arabic',
    'kaa': 'Kara-Kalpak',
    'kab': 'Kabyle',
    'kac': 'Kachin',
    'kal': 'Kalâtdlisut',
    'kam': 'Kamba',
    'kan': 'Kannada',
    'kar': 'Karen languages',
    'kas': 'Kashmiri',
    'kau': 'Kanuri',
    'kaw': 'Kawi',
    'kaz': 'Kazakh',
    'kbd': 'Kabardian',
    'kha': 'Khasi',
    'khi': 'Khoisan (Other)',
    'khm': 'Khmer',
    'kho': 'Khotanese',
    'kik': 'Kikuyu',
    'kin': 'Kinyarwanda',
    'kir': 'Kyrgyz',
    'kmb': 'Kimbundu',
    'kok': 'Konkani',
    'kom': 'Komi',
    'kon': 'Kongo',
    'kor': 'Korean',
    'kos': 'Kosraean',
    'kpe': 'Kpelle',
    'krc': 'Karachay-Balkar',
    'krl': 'Karelian',
    'kro': 'Kru (Other)',
    'kru': 'Kurukh',
    'kua': 'Kuanyama',
    'kum': 'Kumyk',
    'kur': 'Kurdish',
    'kus': 'Kusaie',
    'kut': 'Kootenai',
    'lad': 'Ladino',
    'lah': 'Lahnd?',
    'lam': 'Lamba (Zambia and Congo)',
    'lan': 'Occitan (post 1500)',
    'lao': 'Lao',
    'lap': 'Sami',
    'lat': 'Latin',
    'lav': 'Latvian',
    'lez': 'Lezgian',
    'lim': 'Limburgish',
    'lin': 'Lingala',
    'lit': 'Lithuanian',
    'lol': 'Mongo-Nkundu',
    'loz': 'Lozi',
    'ltz': 'Luxembourgish',
    'lua': 'Luba-Lulua',
    'lub': 'Luba-Katanga',
    'lug': 'Ganda',
    'lui': 'Luiseño',
    'lun': 'Lunda',
    'luo': 'Luo (Kenya and Tanzania)',
    'lus': 'Lushai',
    'mac': 'Macedonian',
    'mad': 'Madurese',
    'mag': 'Magahi',
    'mah': 'Marshallese',
    'mai': 'Maithili',
    'mak': 'Makasar',
    'mal': 'Malayalam',
    'man': 'Mandingo',
    'mao': 'Maori',
    'map': 'Austronesian (Other)',
    'mar': 'Marathi',
    'mas': 'Maasai',
    'max': 'Manx',
    'may': 'Malay',
    'mdf': 'Moksha',
    'mdr': 'Mandar',
    'men': 'Mende',
    'mga': 'Irish, Middle (ca. 1100-1550)',
    'mic': 'Micmac',
    'min': 'Minangkabau',
    'mis': 'Miscellaneous languages',
    'mkh': 'Mon-Khmer (Other)',
    'mla': 'Malagasy',
    'mlg': 'Malagasy',
    'mlt': 'Maltese',
    'mnc': 'Manchu',
    'mni': 'Manipuri',
    'mno': 'Manobo languages',
    'moh': 'Mohawk',
    'mol': 'Moldavian',
    'mon': 'Mongolian',
    'mos': 'Mooré',
    'mul': 'Multiple languages',
    'mun': 'Munda (Other)',
    'mus': 'Creek',
    'mwl': 'Mirandese',
    'mwr': 'Marwari',
    'myn': 'Mayan languages',
    'myv': 'Erzya',
    'nah': 'Nahuatl',
    'nai': 'North American Indian (Other)',
    'nap': 'Neapolitan Italian',
    'nau': 'Nauru',
    'nav': 'Navajo',
    'nbl': 'Ndebele (South Africa)',
    'nde': 'Ndebele (Zimbabwe)',
    'ndo': 'Ndonga',
    'nds': 'Low German',
    'nep': 'Nepali',
    'new': 'Newari',
    'nia': 'Nias',
    'nic': 'Niger-Kordofanian (Other)',
    'niu': 'Niuean',
    'nno': 'Norwegian (Nynorsk)',
    'nob': 'Norwegian (Bokmål)',
    'nog': 'Nogai',
    'non': 'Old Norse',
    'nor': 'Norwegian',
    'nqo': 'N\'Ko',
    'nso': 'Northern Sotho',
    'nub': 'Nubian languages',
    'nwc': 'Newari, Old',
    'nya': 'Nyanja',
    'nym': 'Nyamwezi',
    'nyn': 'Nyankole',
    'nyo': 'Nyoro',
    'nzi': 'Nzima',
    'oci': 'Occitan (post 1500)',
    'oji': 'Ojibwa',
    'ori': 'Oriya',
    'orm': 'Oromo',
    'osa': 'Osage',
    'oss': 'Ossetic',
    'ota': 'Turkish, Ottoman',
    'oto': 'Otomian languages',
    'paa': 'Papuan (Other)',
    'pag': 'Pangasinan',
    'pal': 'Pahlavi',
    'pam': 'Pampanga',
    'pan': 'Panjabi',
    'pap': 'Papiamento',
    'pau': 'Palauan',
    'peo': 'Old Persian (ca. 600-400 B.C.)',
    'per': 'Persian',
    'phi': 'Philippine (Other)',
    'phn': 'Phoenician',
    'pli': 'Pali',
    'pol': 'Polish',
    'pon': 'Pohnpeian',
    'por': 'Portuguese',
    'pra': 'Prakrit languages',
    'pro': 'Provençal (to 1500)',
    'pus': 'Pushto',
    'que': 'Quechua',
    'raj': 'Rajasthani',
    'rap': 'Rapanui',
    'rar': 'Rarotongan',
    'roa': 'Romance (Other)',
    'roh': 'Raeto-Romance',
    'rom': 'Romani',
    'rum': 'Romanian',
    'run': 'Rundi',
    'rup': 'Aromanian',
    'rus': 'Russian',
    'sad': 'Sandawe',
    'sag': 'Sango (Ubangi Creole)',
    'sah': 'Yakut',
    'sai': 'South American Indian (Other)',
    'sal': 'Salishan languages',
    'sam': 'Samaritan Aramaic',
    'san': 'Sanskrit',
    'sao': 'Samoan',
    'sas': 'Sasak',
    'sat': 'Santali',
    'scc': 'Serbian',
    'scn': 'Sicilian Italian',
    'sco': 'Scots',
    'scr': 'Croatian',
    'sel': 'Selkup',
    'sem': 'Semitic (Other)',
    'sga': 'Irish, Old (to 1100)',
    'sgn': 'Sign languages',
    'shn': 'Shan',
    'sho': 'Shona',
    'sid': 'Sidamo',
    'sin': 'Sinhalese',
    'sio': 'Siouan (Other)',
    'sit': 'Sino-Tibetan (Other)',
    'sla': 'Slavic (Other)',
    'slo': 'Slovak',
    'slv': 'Slovenian',
    'sma': 'Southern Sami',
    'sme': 'Northern Sami',
    'smi': 'Sami',
    'smj': 'Lule Sami',
    'smn': 'Inari Sami',
    'smo': 'Samoan',
    'sms': 'Skolt Sami',
    'sna': 'Shona',
    'snd': 'Sindhi',
    'snh': 'Sinhalese',
    'snk': 'Soninke',
    'sog': 'Sogdian',
    'som': 'Somali',
    'son': 'Songhai',
    'sot': 'Sotho',
    'spa': 'Spanish',
    'srd': 'Sardinian',
    'srn': 'Sranan',
    'srp': 'Serbian',
    'srr': 'Serer',
    'ssa': 'Nilo-Saharan (Other)',
    'sso': 'Sotho',
    'ssw': 'Swazi',
    'suk': 'Sukuma',
    'sun': 'Sundanese',
    'sus': 'Susu',
    'sux': 'Sumerian',
    'swa': 'Swahili',
    'swe': 'Swedish',
    'swz': 'Swazi',
    'syc': 'Syriac',
    'syr': 'Syriac, Modern',
    'tag': 'Tagalog',
    'tah': 'Tahitian',
    'tai': 'Tai (Other)',
    'taj': 'Tajik',
    'tam': 'Tamil',
    'tar': 'Tatar',
    'tat': 'Tatar',
    'tel': 'Telugu',
    'tem': 'Temne',
    'ter': 'Terena',
    'tet': 'Tetum',
    'tgk': 'Tajik',
    'tgl': 'Tagalog',
    'tha': 'Thai',
    'tib': 'Tibetan',
    'tig': 'Tigré',
    'tir': 'Tigrinya',
    'tiv': 'Tiv',
    'tkl': 'Tokelauan',
    'tlh': 'Klingon (Artificial language)',
    'tli': 'Tlingit',
    'tmh': 'Tamashek',
    'tog': 'Tonga (Nyasa)',
    'ton': 'Tongan',
    'tpi': 'Tok Pisin',
    'tru': 'Truk',
    'tsi': 'Tsimshian',
    'tsn': 'Tswana',
    'tso': 'Tsonga',
    'tsw': 'Tswana',
    'tuk': 'Turkmen',
    'tum': 'Tumbuka',
    'tup': 'Tupi languages',
    'tur': 'Turkish',
    'tut': 'Altaic (Other)',
    'tvl': 'Tuvaluan',
    'twi': 'Twi',
    'tyv': 'Tuvinian',
    'udm': 'Udmurt',
    'uga': 'Ugaritic',
    'uig': 'Uighur',
    'ukr': 'Ukrainian',
    'umb': 'Umbundu',
    'und': 'Undetermined',
    'urd': 'Urdu',
    'uzb': 'Uzbek',
    'vai': 'Vai',
    'ven': 'Venda',
    'vie': 'Vietnamese',
    'vol': 'Volapük',
    'vot': 'Votic',
    'wak': 'Wakashan languages',
    'wal': 'Wolayta',
    'war': 'Waray',
    'was': 'Washoe',
    'wel': 'Welsh',
    'wen': 'Sorbian (Other)',
    'wln': 'Walloon',
    'wol': 'Wolof',
    'xal': 'Oirat',
    'xho': 'Xhosa',
    'yao': 'Yao (Africa)',
    'yap': 'Yapese',
    'yid': 'Yiddish',
    'yor': 'Yoruba',
    'ypk': 'Yupik languages',
    'zap': 'Zapotec',
    'zbl': 'Blissymbolics',
    'zen': 'Zenaga',
    'zha': 'Zhuang',
    'znd': 'Zande languages',
    'zul': 'Zulu',
    'zun': 'Zuni',
    'zxx': 'No linguistic content',
    'zza': 'Zaza',
}

video_techniques = {
    'a': 'Animation',
    'c': 'Animation and live action',
    'l': 'Live action'
}

# http://www.loc.gov/marc/countries/countries_code.html
country_codes = {
    'aa': 'Albania',
    'abc': 'Alberta',
    'ac': 'Ashmore and Cartier Islands',
    'aca': 'Australian Capital Territory',
    'ae': 'Algeria',
    'af': 'Afghanistan',
    'ag': 'Argentina',
    'ai': 'Anguilla',
    'ai': 'Armenia (Republic)',
    'air': 'Armenian S.S.R.',
    'aj': 'Azerbaijan',
    'ajr': 'Azerbaijan S.S.R.',
    'aku': 'Alaska',
    'alu': 'Alabama',
    'am': 'Anguilla',
    'an': 'Andorra',
    'ao': 'Angola',
    'aq': 'Antigua and Barbuda',
    'aru': 'Arkansas',
    'as': 'American Samoa',
    'at': 'Australia',
    'au': 'Austria',
    'aw': 'Aruba',
    'ay': 'Antarctica',
    'azu': 'Arizona',
    'ba': 'Bahrain',
    'bb': 'Barbados',
    'bcc': 'British Columbia',
    'bd': 'Burundi',
    'be': 'Belgium',
    'bf': 'Bahamas',
    'bg': 'Bangladesh',
    'bh': 'Belize',
    'bi': 'British Indian Ocean Territory',
    'bl': 'Brazil',
    'bm': 'Bermuda Islands',
    'bn': 'Bosnia and Hercegovina',
    'bo': 'Bolivia',
    'bp': 'Solomon Islands',
    'br': 'Burma',
    'bs': 'Botswana',
    'bt': 'Bhutan',
    'bu': 'Bulgaria',
    'bv': 'Bouvet Island',
    'bw': 'Belarus',
    'bwr': 'Byelorussian S.S.R.',
    'bx': 'Brunei',
    'ca': 'Caribbean Netherlands',
    'cau': 'California',
    'cb': 'Cambodia',
    'cc': 'China',
    'cd': 'Chad',
    'ce': 'Sri Lanka',
    'cf': 'Congo (Brazzaville)',
    'cg': 'Congo (Democratic Republic)',
    'ch': 'China (Republic : 1949- )',
    'ci': 'Croatia',
    'cj': 'Cayman Islands',
    'ck': 'Colombia',
    'cl': 'Chile',
    'cm': 'Cameroon',
    'cn': 'Canada',
    'co': 'Curaçao',
    'cou': 'Colorado',
    'cp': 'Canton and Enderbury Islands',
    'cq': 'Comoros',
    'cr': 'Costa Rica',
    'cs': 'Czechoslovakia',
    'ctu': 'Connecticut',
    'cu': 'Cuba',
    'cv': 'Cape Verde',
    'cw': 'Cook Islands',
    'cx': 'Central African Republic',
    'cy': 'Cyprus',
    'cz': 'Canal Zone',
    'dcu': 'District of Columbia',
    'deu': 'Delaware',
    'dk': 'Denmark',
    'dm': 'Benin',
    'dq': 'Dominica',
    'dr': 'Dominican Republic',
    'ea': 'Eritrea',
    'ec': 'Ecuador',
    'eg': 'Equatorial Guinea',
    'em': 'Timor-Leste',
    'enk': 'England',
    'er': 'Estonia',
    'err': 'Estonia',
    'es': 'El Salvador',
    'et': 'Ethiopia',
    'fa': 'Faroe Islands',
    'fg': 'French Guiana',
    'fi': 'Finland',
    'fj': 'Fiji',
    'fk': 'Falkland Islands',
    'flu': 'Florida',
    'fm': 'Micronesia (Federated States)',
    'fp': 'French Polynesia',
    'fr': 'France',
    'fs': 'Terres australes et antarctiques françaises',
    'ft': 'Djibouti',
    'gau': 'Georgia',
    'gb': 'Kiribati',
    'gd': 'Grenada',
    'ge': 'Germany (East)',
    'gh': 'Ghana',
    'gi': 'Gibraltar',
    'gl': 'Greenland',
    'gm': 'Gambia',
    'gn': 'Gilbert and Ellice Islands',
    'go': 'Gabon',
    'gp': 'Guadeloupe',
    'gr': 'Greece',
    'gs': 'Georgia (Republic)',
    'gsr': 'Georgian S.S.R.',
    'gt': 'Guatemala',
    'gu': 'Guam',
    'gv': 'Guinea',
    'gw': 'Germany',
    'gy': 'Guyana',
    'gz': 'Gaza Strip',
    'hiu': 'Hawaii',
    'hk': 'Hong Kong',
    'hm': 'Heard and McDonald Islands',
    'ho': 'Honduras',
    'ht': 'Haiti',
    'hu': 'Hungary',
    'iau': 'Iowa',
    'ic': 'Iceland',
    'idu': 'Idaho',
    'ie': 'Ireland',
    'ii': 'India',
    'ilu': 'Illinois',
    'inu': 'Indiana',
    'io': 'Indonesia',
    'iq': 'Iraq',
    'ir': 'Iran',
    'is': 'Israel',
    'it': 'Italy',
    'iu': 'Israel-Syria Demilitarized Zones',
    'iv': 'Côte d\'Ivoire',
    'iw': 'Israel-Jordan Demilitarized Zones',
    'iy': 'Iraq-Saudi Arabia Neutral Zone',
    'ja': 'Japan',
    'ji': 'Johnston Atoll',
    'jm': 'Jamaica',
    'jn': 'Jan Mayen',
    'jo': 'Jordan',
    'ke': 'Kenya',
    'kg': 'Kyrgyzstan',
    'kgr': 'Kirghiz S.S.R.',
    'kn': 'Korea (North)',
    'ko': 'Korea (South)',
    'ksu': 'Kansas',
    'ku': 'Kuwait',
    'kv': 'Kosovo',
    'kyu': 'Kentucky',
    'kz': 'Kazakhstan',
    'kzr': 'Kazakh S.S.R.',
    'lau': 'Louisiana',
    'lb': 'Liberia',
    'le': 'Lebanon',
    'lh': 'Liechtenstein',
    'li': 'Lithuania',
    'lir': 'Lithuania',
    'ln': 'Central and Southern Line Islands',
    'lo': 'Lesotho',
    'ls': 'Laos',
    'lu': 'Luxembourg',
    'lv': 'Latvia',
    'lvr': 'Latvia',
    'ly': 'Libya',
    'mau': 'Massachusetts',
    'mbc': 'Manitoba',
    'mc': 'Monaco',
    'mdu': 'Maryland',
    'meu': 'Maine',
    'mf': 'Mauritius',
    'mg': 'Madagascar',
    'mh': 'Macao',
    'miu': 'Michigan',
    'mj': 'Montserrat',
    'mk': 'Oman',
    'ml': 'Mali',
    'mm': 'Malta',
    'mnu': 'Minnesota',
    'mo': 'Montenegro',
    'mou': 'Missouri',
    'mp': 'Mongolia',
    'mq': 'Martinique',
    'mr': 'Morocco',
    'msu': 'Mississippi',
    'mtu': 'Montana',
    'mu': 'Mauritania',
    'mv': 'Moldova',
    'mvr': 'Moldavian S.S.R.',
    'mw': 'Malawi',
    'mx': 'Mexico',
    'my': 'Malaysia',
    'mz': 'Mozambique',
    'na': 'Netherlands Antilles',
    'nbu': 'Nebraska',
    'ncu': 'North Carolina',
    'ndu': 'North Dakota',
    'ne': 'Netherlands',
    'nfc': 'Newfoundland and Labrador',
    'ng': 'Niger',
    'nhu': 'New Hampshire',
    'nik': 'Northern Ireland',
    'nju': 'New Jersey',
    'nkc': 'New Brunswick',
    'nl': 'New Caledonia',
    'nm': 'Northern Mariana Islands',
    'nmu': 'New Mexico',
    'nn': 'Vanuatu',
    'no': 'Norway',
    'np': 'Nepal',
    'nq': 'Nicaragua',
    'nr': 'Nigeria',
    'nsc': 'Nova Scotia',
    'ntc': 'Northwest Territories',
    'nu': 'Nauru',
    'nuc': 'Nunavut',
    'nvu': 'Nevada',
    'nw': 'Northern Mariana Islands',
    'nx': 'Norfolk Island',
    'nyu': 'New York (State)',
    'nz': 'New Zealand',
    'ohu': 'Ohio',
    'oku': 'Oklahoma',
    'onc': 'Ontario',
    'oru': 'Oregon',
    'ot': 'Mayotte',
    'pau': 'Pennsylvania',
    'pc': 'Pitcairn Island',
    'pe': 'Peru',
    'pf': 'Paracel Islands',
    'pg': 'Guinea-Bissau',
    'ph': 'Philippines',
    'pic': 'Prince Edward Island',
    'pk': 'Pakistan',
    'pl': 'Poland',
    'pn': 'Panama',
    'po': 'Portugal',
    'pp': 'Papua New Guinea',
    'pr': 'Puerto Rico',
    'pt': 'Portuguese Timor',
    'pw': 'Palau',
    'py': 'Paraguay',
    'qa': 'Qatar',
    'qea': 'Queensland',
    'quc': 'Québec (Province)',
    'rb': 'Serbia',
    're': 'Réunion',
    'rh': 'Zimbabwe',
    'riu': 'Rhode Island',
    'rm': 'Romania',
    'ru': 'Russia (Federation)',
    'rur': 'Russian S.F.S.R.',
    'rw': 'Rwanda',
    'ry': 'Ryukyu Islands, Southern',
    'sa': 'South Africa',
    'sb': 'Svalbard',
    'sc': 'Saint-Barthélemy',
    'scu': 'South Carolina',
    'sd': 'South Sudan',
    'sdu': 'South Dakota',
    'se': 'Seychelles',
    'sf': 'Sao Tome and Principe',
    'sg': 'Senegal',
    'sh': 'Spanish North Africa',
    'si': 'Singapore',
    'sj': 'Sudan',
    'sk': 'Sikkim',
    'sl': 'Sierra Leone',
    'sm': 'San Marino',
    'sn': 'Sint Maarten',
    'snc': 'Saskatchewan',
    'so': 'Somalia',
    'sp': 'Spain',
    'sq': 'Swaziland',
    'sr': 'Surinam',
    'ss': 'Western Sahara',
    'st': 'Saint-Martin',
    'stk': 'Scotland',
    'su': 'Saudi Arabia',
    'sv': 'Swan Islands',
    'sw': 'Sweden',
    'sx': 'Namibia',
    'sy': 'Syria',
    'sz': 'Switzerland',
    'ta': 'Tajikistan',
    'tar': 'Tajik S.S.R.',
    'tc': 'Turks and Caicos Islands',
    'tg': 'Togo',
    'th': 'Thailand',
    'ti': 'Tunisia',
    'tk': 'Turkmenistan',
    'tkr': 'Turkmen S.S.R.',
    'tl': 'Tokelau',
    'tma': 'Tasmania',
    'tnu': 'Tennessee',
    'to': 'Tonga',
    'tr': 'Trinidad and Tobago',
    'ts': 'United Arab Emirates',
    'tt': 'Trust Territory of the Pacific Islands',
    'tu': 'Turkey',
    'tv': 'Tuvalu',
    'txu': 'Texas',
    'tz': 'Tanzania',
    'ua': 'Egypt',
    'uc': 'United States Misc. Caribbean Islands',
    'ug': 'Uganda',
    'ui': 'United Kingdom Misc. Islands',
    'uik': 'United Kingdom Misc. Islands',
    'uk': 'United Kingdom',
    'un': 'Ukraine',
    'unr': 'Ukraine',
    'up': 'United States Misc. Pacific Islands',
    'ur': 'Soviet Union',
    'us': 'United States',
    'utu': 'Utah',
    'uv': 'Burkina Faso',
    'uy': 'Uruguay',
    'uz': 'Uzbekistan',
    'uzr': 'Uzbek S.S.R.',
    'vau': 'Virginia',
    'vb': 'British Virgin Islands',
    'vc': 'Vatican City',
    've': 'Venezuela',
    'vi': 'Virgin Islands of the United States',
    'vm': 'Vietnam',
    'vn': 'Vietnam, North',
    'vp': 'Various places',
    'vra': 'Victoria',
    'vs': 'Vietnam, South',
    'vtu': 'Vermont',
    'wau': 'Washington (State)',
    'wb': 'West Berlin',
    'wea': 'Western Australia',
    'wf': 'Wallis and Futuna',
    'wiu': 'Wisconsin',
    'wj': 'West Bank of the Jordan River',
    'wk': 'Wake Island',
    'wlk': 'Wales',
    'ws': 'Samoa',
    'wvu': 'West Virginia',
    'wyu': 'Wyoming',
    'xa': 'Christmas Island (Indian Ocean)',
    'xb': 'Cocos (Keeling) Islands',
    'xc': 'Maldives',
    'xd': 'Saint Kitts-Nevis',
    'xe': 'Marshall Islands',
    'xf': 'Midway Islands',
    'xga': 'Coral Sea Islands Territory',
    'xh': 'Niue',
    'xi': 'Saint Kitts-Nevis-Anguilla',
    'xj': 'Saint Helena',
    'xk': 'Saint Lucia',
    'xl': 'Saint Pierre and Miquelon',
    'xm': 'Saint Vincent and the Grenadines',
    'xn': 'Macedonia',
    'xna': 'New South Wales',
    'xo': 'Slovakia',
    'xoa': 'Northern Territory',
    'xp': 'Spratly Island',
    'xr': 'Czech Republic',
    'xra': 'South Australia',
    'xs': 'South Georgia and the South Sandwich Islands',
    'xv': 'Slovenia',
    'xx': 'No place, unknown, or undetermined',
    'xxc': 'Canada',
    'xxk': 'United Kingdom',
    'xxr': 'Soviet Union',
    'xxu': 'United States',
    'ye': 'Yemen',
    'ykc': 'Yukon Territory',
    'ys': 'Yemen (People\'s Democratic Republic)',
    'yu': 'Serbia and Montenegro',
    'za': 'Zambia',
}
